### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by ibooj** [miguelramos/django-media-manager#23]
Collecting django-media-manager
  Using cached django-media-manager-3.3.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Django>=1.5 in ../python3.5/site-packages (from django-media-manager)
Collecting PIL (from django-media-manager)

  Could not find a version that satisfies the requirement PIL (from django-media-manager) (from versions: )
No matching distribution found for PIL (from django-media-manager)

**Comment by miguelramos** [comment]
Please try the new version deployed by contributors.
